# Generated by Django 5.0.6 on 2024-07-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
