# Generated by Django 5.0.6 on 2024-07-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comments_options_alter_likes_options_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='news',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
