# Generated by Django 5.0.6 on 2024-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_likes_news_remove_likes_user_delete_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
