# Generated by Django 5.0.6 on 2024-07-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_likes_news_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='like',
            new_name='likes',
        ),
    ]
