# Generated by Django 5.0.6 on 2024-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_news_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
