# Generated by Django 5.0.6 on 2024-07-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_news_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment',
        ),
    ]
